In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import pickle
import numpy as np
from ydata_profiling import ProfileReport

In [4]:
df = pd.read_csv('C:/Users/akhil/OneDrive/Desktop/hypothesis/Advertising.csv' )

# Advertising Data

This dataset contains information about advertising expenditures and sales. The columns represent the following:

- **Unnamed: 0**: Index of the data points.
- **TV**: Advertising budget spent on TV (in thousands of dollars).
- **Radio**: Advertising budget spent on Radio (in thousands of dollars).
- **Newspaper**: Advertising budget spent on Newspaper (in thousands of dollars).
- **Sales**: Sales of the product (in thousands of units).

In [5]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

## Explanation of the Data

**Unnamed: 0:** This is just an index column, which is often used to uniquely identify each row in the dataset.

**TV:** The amount of money spent on TV advertising for each data point. For example, the first entry spent $230.1k on TV ads.

**Radio:** The amount of money spent on radio advertising. The first entry spent $37.8k on radio ads.

**Newspaper:** The amount of money spent on newspaper advertising. The first entry spent $69.2k on newspaper ads.

**Sales:** The sales figures corresponding to the advertising spend. The first entry achieved sales of 22.1k units.

In [6]:
df.describe()

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

## Exploratory Data Analysis

 Here we trying taken a one feature and trying to predict ( finding relationship) with sales. 

In [8]:
pf= ProfileReport(df)

In [9]:
pf.to_widgets()

I can see a linear relationship with TV and sales , So we can apply Lineaar Regression on these variable. 

In [21]:
x = df[['TV']]
x

TV
0    230.1
1     44.5
2     17.2
3    151.5
4    180.8
..     ...
195   38.2
196   94.2
197  177.0
198  283.6
199  232.1

[200 rows x 1 columns]

In [17]:
#y = df['Sales']
y = df.Sales
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [22]:
from sklearn.linear_model import LinearRegression
linear = LinearRegression()
# In this step we will find m and c values.
linear.fit(x,y)

LinearRegression()

In [23]:
linear.intercept_

7.032593549127695

In [24]:
linear.coef_

array([0.04753664])

In [25]:
# for saving the model
file = 'linear_regression.sav'
pickle.dump(linear,open(file,'wb'))

In [27]:
linear.predict([[40]])

C:\Users\akhil\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8.93405917])

In [29]:
l = [3,4,83,65,66,44,663,2,24,6,40]
for i in l:
    print(linear.predict([[i]]))

[7.17520347]
[7.22274011]
[10.97813471]
[10.12247518]
[10.17001182]
[9.12420573]
[38.54938616]
[7.12766683]
[8.17347292]
[7.31781339]
[8.93405917]


C:\Users\akhil\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\akhil\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\akhil\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\akhil\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
C:\Users\akhil\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [30]:
saved_model=pickle.load(open(file,'rb'))

In [32]:
saved_model.predict([[40]])

C:\Users\akhil\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8.93405917])

In [33]:
linear.score(x,y)

0.611875050850071

In [ ]:
]